# Sorting Arrays

Sorting problem은 매우 빈번하게 발생하는 중요한 계산 문제이다. 

여기에서는 array를 정렬하는 NumPy 함수를 소개한다. 


In [0]:
import numpy as np


## Fast Sorting in NumPy: ``np.sort`` and ``np.argsort``

Python built-in ``sort`` 혹은 ``sorted``함수를 통해 list를 정렬할 수 있지만, NumPy의 ``np.sort`` 함수가 일반적으로 더 빠르다.

``np.sort``는 default로 $\mathcal{O}[N\log N]$, *quicksort* algorithm을 사용하며 *mergesort*와 *heapsort*도 사용 가능하다. 

In [5]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

in-place sort를 원한다면 객체의 ``sort`` method를 이용하면 된다.

In [6]:
x.sort()
print(x)

[1 2 3 4 5]


``argsort`` 함수는 *indices* of the sorted elements를 리턴한다.

In [7]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


앞서 배운 fancy indexing과 결합하면 sorted array 결과를 얻을 수 있다. 

In [8]:
x[i]

array([1, 2, 3, 4, 5])

### Sorting along rows or columns

NumPy의 sort 함수의 특징 중 하나는 multidimensional array의 특정 axis를 기준으로 정렬할 수 있다는 점이다. (``axis`` argument를 사용)

In [9]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [10]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [11]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Partial Sorts: Partitioning

전체를 정렬하지 않고 가장 작은 값 *k*개를 array 왼쪽편에 배치한다. 

``np.partition``함수를 이용할 수 있다. 

In [12]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [13]:
np.partition(X, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])