# Aggregations: Min, Max, and Everything In Between

데이터에서 특징값이나 대표값을 계산하는 것은 매우 빈번하다.
 - 평균, 표준편차
 - 최소값, 최대값, 중간값, 분위값 등

NumPy는 그러한 계산을 위한 built-in  function들을 제공한다. 

## Summing the Values in an Array


In [0]:
import numpy as np

In [0]:
L = np.random.random(100)
sum(L)

50.43442608025276

NumPy 패키지의 ``sum`` 함수를 똑같이 사용할 수 있다.

In [0]:
np.sum(L)

50.434426080252756

그러나 NumPy version 이 훨씬 빠르다.

In [0]:
big_array = np.random.rand(10000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

1 loop, best of 3: 1.62 s per loop
100 loops, best of 3: 6.52 ms per loop


## Minimum and Maximum

Python built-in function인 ``min``과  ``max``를 통해 최소값과 최대값을 구할 수 있다. 

In [0]:
min(big_array), max(big_array)

(4.6078531767967945e-08, 0.9999997245428011)

마찬가지로 NumPy version이 존재하며 더 빠르다. 

In [0]:
np.min(big_array), np.max(big_array)

(4.6078531767967945e-08, 0.9999997245428011)

In [0]:
%timeit min(big_array)
%timeit np.min(big_array)

1 loop, best of 3: 1.04 s per loop
100 loops, best of 3: 6.66 ms per loop


Object method를 호출하는 형태도 가능하다.

In [0]:
print(big_array.min(), big_array.max(), big_array.sum())
%timeit big_array.min()

4.6078531767967945e-08 0.9999997245428011 4999415.412017119
100 loops, best of 3: 6.69 ms per loop


### Multi dimensional aggregates

Muti-dimensional array에서도 가능하며, row 혹은 column 단위 적용에도 유용하다. 

In [0]:
M = np.random.random((3, 4))
print(M)

[[0.65604306 0.96853645 0.93512625 0.77502055]
 [0.39035772 0.90988718 0.17264536 0.63358973]
 [0.24967066 0.17549295 0.27048744 0.37457659]]


In [0]:
M.sum()

6.511433942387229

*axis* argument를 통해 축을 지정할 수 있다. 

In [0]:
M.min(axis=0)

array([0.24967066, 0.17549295, 0.17264536, 0.37457659])

In [0]:
M.max(axis=1)

array([0.96853645, 0.90988718, 0.37457659])

In [0]:
X=np.random.random((3,4,5))
print(X)
print(X.min(axis=0))
print(X.min(axis=2))

[[[0.27497542 0.18419718 0.63078971 0.17495724 0.72054327]
  [0.53745451 0.37170028 0.18056468 0.76170391 0.49817015]
  [0.22122038 0.42267259 0.49447539 0.59453842 0.6005164 ]
  [0.56876451 0.33111399 0.36700712 0.8411225  0.03330977]]

 [[0.85649359 0.2989195  0.31681903 0.6354031  0.27555436]
  [0.87472597 0.86795728 0.48902525 0.03536462 0.4522702 ]
  [0.6163586  0.19073182 0.98067004 0.43706254 0.05017668]
  [0.3132046  0.69678637 0.42208012 0.99984611 0.7831699 ]]

 [[0.228274   0.80276581 0.40455803 0.52842503 0.72132862]
  [0.76621102 0.19572265 0.65961482 0.12739426 0.53022677]
  [0.72512699 0.57685433 0.0397647  0.62721341 0.97699659]
  [0.23835087 0.32261936 0.52108228 0.63458585 0.83503698]]]
[[0.228274   0.18419718 0.31681903 0.17495724 0.27555436]
 [0.53745451 0.19572265 0.18056468 0.03536462 0.4522702 ]
 [0.22122038 0.19073182 0.0397647  0.43706254 0.05017668]
 [0.23835087 0.32261936 0.36700712 0.63458585 0.03330977]]
[[0.17495724 0.18056468 0.22122038 0.03330977]
 [0.27

### Other aggregation functions


|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

