# Chapter 3. Sequences
- Arrays (배열)
- Ranges (범주)

In [1]:
from datascience import *
english_parts_of_speech = make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")
english_parts_of_speech

/usr/local/lib/python3.7/dist-packages/datascience/tables.py:17: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  matplotlib.use('agg', warn=False)
/usr/local/lib/python3.7/dist-packages/datascience/util.py:10: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  matplotlib.use('agg', warn=False)


array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'], dtype='<U12')

In [2]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, baseline_high - 0.093,
                   baseline_high + 0.105, baseline_high + 0.684)
highs

array([13.6  , 14.387, 14.585, 15.164])

앞서 공부한 바와 같이 array 변수를 수식에 사용 가능하며  벡터 연산으로 효율적이다.
 - 다음 예들을 포함하여 numpy 의 많은 function/method를 사용한다.

- 입력: array, 출력: single value

|Function|Description|
--|--
| np.prod | Multiply all elements together |
| np.sum  | Add all elements together |
| np.all  | Test whether all elements are true values (non-zero numbers are true) |
| np.any  | Test whether any elements are true values (non-zero numbers are true) |
| np.count_nonzero  | Count the number of non-zero elements |


- 입력: array, 출력: array

|Function|Description|
--|--
| np.diff   | Difference between adjacent elements |
| np.round  | Round each number to the nearest integer (whole number) |
| np.cumprod  | A cumulative product: for each element, multiply all elements so far  |
| np.exp  | Exponentiate each element |
| np.log  | Take the natural logarithm of each element |
| np.sqrt  | Take the square root of each element |
| np.sort  | Sort the elements |

- 입력: string(즉, 문자array), 출력: array

|Function|Description|
--|--
| np.char.lower   | Lowercase each element |
|  np.char.upper   | Uppercase each element |
| np.char.strip   |Remove spaces at the beginning or end of each element  |
|  np.char.isalpha    | Whether each element is only letters (no numbers or symbols) |
|  np.char.isnumeric  | Whether each element is only numeric (no letters) |

- 입력: string과 탐색 string , 출력: array

|Function|Description|
--|--
|  np.char.count    | Count the number of times a search string appears among the elements of an array |
|  np.char.find    | The position within each element that a search string is found first |
|  np.char.rfind   | The position within each element that a search string is found last  |
|  np.char.startswith     | Whether each element starts with the search string |

Range
 - 증가 혹은 감소하는 숫자 배열
 - interval을 표시하는데 사용
 - np.arange()를 이용하여 생성
 - arguments: start, end, step 값
 - 주의) start는 포함하지만 end는 불포함

In [3]:
import numpy as np
np.arange(5)


array([0, 1, 2, 3, 4])

In [4]:
np.arange(3, 9)
np.arange(3, 30, 5)
np.arange(1.5, -2, -0.5)

array([ 1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5])

#### RECAP
- Arrays
 - 같은 데이터형의 집합을 다루는 데 유용
- Ranges
 - 같은 간격의 수열